# sudo python3 installer.py
import os, time, sys

os.system('clear')
os.system('sudo apt update -y && sudo apt upgrade -y') 
os.system('sudo apt install nodejs -y')
os.system('sudo apt install npm -y')
os.system('sudo apt install python3 -y')
os.system('sudo apt install python3-pip -y')
os.system('npm i user-agents')
os.system('npm i colors')
os.system('npm i hpack')
os.system('npm i axios')
os.system('npm i cheerio')
os.system('npm i node-fetch')
os.system('npm i gradient-string')
os.system('npm i fake-useragent')
os.system('npm i header-generator')
os.system('npm i readline-sync')
os.system('npm i hpack node-fetch node-fetch@2 socks dns colors')
os.system('npm i random-useragent')
os.system('pip install colorama request')
time.sleep(1)
os.system('clear')
time.sleep(5)
print("Buka File Module.txt dan salin text itu dan paste ke vps agar mendownload module yang di perlukan")
time.sleep(7)
sys.exit()